server:
  port: 0

spring:
  application:
    name: event-service
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/ewmEventDB}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.zalando.logbook: TRACE

resilience4j:
  retry:
    instances:
      request-service:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      request-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewmEventDB
    username: root
    password: root