server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**,/admin/**,/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/event/**,/comments/**
        - id: collector
          uri: lb://collector
          predicates:
            - Path=/collector/**
        - id: analyzer
          uri: lb://analyzer
          predicates:
            - Path=/analyzer/**
        - id: aggregator
          uri: lb://aggregator
          predicates:
            - Path=/aggregator/**
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
